version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - data:/data

volumes:
  data:
